//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlnUtils {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonLocalizableStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonLocalizableStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SlnUtils.CommonLocalizableStrings", typeof(CommonLocalizableStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} is invalid..
        /// </summary>
        internal static string ArgumentIsInvalid {
            get {
                return ResourceManager.GetString("ArgumentIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project or solution to operation on. If a file is not specified, the current directory is searched..
        /// </summary>
        internal static string ArgumentsProjectOrSolutionDescription {
            get {
                return ResourceManager.GetString("ArgumentsProjectOrSolutionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create shell shim for an empty command..
        /// </summary>
        internal static string CannotCreateShimForEmptyCommand {
            get {
                return ResourceManager.GetString("CannotCreateShimForEmptyCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create shell shim for an empty executable path..
        /// </summary>
        internal static string CannotCreateShimForEmptyExecutablePath {
            get {
                return ResourceManager.GetString("CannotCreateShimForEmptyExecutablePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRAMEWORK.
        /// </summary>
        internal static string CmdFramework {
            get {
                return ResourceManager.GetString("CmdFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the value of the $(VersionSuffix) property to use when building the project..
        /// </summary>
        internal static string CmdVersionSuffixDescription {
            get {
                return ResourceManager.GetString("CmdVersionSuffixDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column maximum width must be greater than zero..
        /// </summary>
        internal static string ColumnMaxWidthMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("ColumnMaxWidthMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows the command to stop and wait for user input or action (for example to complete authentication)..
        /// </summary>
        internal static string CommandInteractiveOptionDescription {
            get {
                return ResourceManager.GetString("CommandInteractiveOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIGURATION.
        /// </summary>
        internal static string ConfigurationArgumentName {
            get {
                return ResourceManager.GetString("ConfigurationArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect with the server..
        /// </summary>
        internal static string CouldNotConnectWithTheServer {
            get {
                return ResourceManager.GetString("CouldNotConnectWithTheServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find any project in `{0}`..
        /// </summary>
        internal static string CouldNotFindAnyProjectInDirectory {
            get {
                return ResourceManager.GetString("CouldNotFindAnyProjectInDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find project or directory `{0}`..
        /// </summary>
        internal static string CouldNotFindProjectOrDirectory {
            get {
                return ResourceManager.GetString("CouldNotFindProjectOrDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified solution file {0} does not exist, or there is no solution file in the directory..
        /// </summary>
        internal static string CouldNotFindSolutionIn {
            get {
                return ResourceManager.GetString("CouldNotFindSolutionIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find solution or directory `{0}`..
        /// </summary>
        internal static string CouldNotFindSolutionOrDirectory {
            get {
                return ResourceManager.GetString("CouldNotFindSolutionOrDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update the version of the package `{0}`..
        /// </summary>
        internal static string CouldNotUpdateTheVersion {
            get {
                return ResourceManager.GetString("CouldNotUpdateTheVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        internal static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools directory &apos;{0}&apos; is not currently on the PATH environment variable.
        ///If you are using bash, you can add it to your profile by running the following command:
        ///
        ///cat &lt;&lt; \EOF &gt;&gt; ~/.bash_profile
        ///# Add .NET Core SDK tools
        ///export PATH=&quot;$PATH:{0}&quot;
        ///EOF
        ///
        ///You can add it to the current session by running the following command:
        ///
        ///export PATH=&quot;$PATH:{0}&quot;
        ///.
        /// </summary>
        internal static string EnvironmentPathLinuxManualInstructions {
            get {
                return ResourceManager.GetString("EnvironmentPathLinuxManualInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since you just installed the .NET Core SDK, you will need to logout or restart your session before running the tool you installed..
        /// </summary>
        internal static string EnvironmentPathLinuxNeedLogout {
            get {
                return ResourceManager.GetString("EnvironmentPathLinuxNeedLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools directory &apos;{0}&apos; is not currently on the PATH environment variable.
        ///If you are using bash, you can add it to your profile by running the following command:
        ///
        ///cat &lt;&lt; \EOF &gt;&gt; ~/.bash_profile
        ///# Add .NET Core SDK tools
        ///export PATH=&quot;$PATH:{0}&quot;
        ///EOF
        ///
        ///You can add it to the current session by running the following command:
        ///
        ///export PATH=&quot;$PATH:{0}&quot;
        ///.
        /// </summary>
        internal static string EnvironmentPathOSXBashManualInstructions {
            get {
                return ResourceManager.GetString("EnvironmentPathOSXBashManualInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since you just installed the .NET Core SDK, you will need to reopen terminal before running the tool you installed..
        /// </summary>
        internal static string EnvironmentPathOSXNeedReopen {
            get {
                return ResourceManager.GetString("EnvironmentPathOSXNeedReopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools directory &apos;{0}&apos; is not currently on the PATH environment variable.
        ///If you are using zsh, you can add it to your profile by running the following command:
        ///
        ///cat &lt;&lt; \EOF &gt;&gt; ~/.zprofile
        ///# Add .NET Core SDK tools
        ///export PATH=&quot;$PATH:{0}&quot;
        ///EOF
        ///
        ///And run `zsh -l` to make it available for current session.
        ///
        ///You can only add it to the current session by running the following command:
        ///
        ///export PATH=&quot;$PATH:{0}&quot;
        ///.
        /// </summary>
        internal static string EnvironmentPathOSXZshManualInstructions {
            get {
                return ResourceManager.GetString("EnvironmentPathOSXZshManualInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools directory &apos;{0}&apos; is not currently on the PATH environment variable.
        ///
        ///You can add the directory to the PATH by running the following command:
        ///
        ///setx PATH &quot;%PATH%;{0}&quot;
        ///.
        /// </summary>
        internal static string EnvironmentPathWindowsManualInstructions {
            get {
                return ResourceManager.GetString("EnvironmentPathWindowsManualInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since you just installed the .NET Core SDK, you will need to reopen the Command Prompt window before running the tool you installed..
        /// </summary>
        internal static string EnvironmentPathWindowsNeedReopen {
            get {
                return ResourceManager.GetString("EnvironmentPathWindowsNeedReopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is already up-to-date..
        /// </summary>
        internal static string EverythingUpToDate {
            get {
                return ResourceManager.GetString("EverythingUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable.
        /// </summary>
        internal static string Executable {
            get {
                return ResourceManager.GetString("Executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set user executable permissions for shell shim: {0}.
        /// </summary>
        internal static string FailedSettingShimPermissions {
            get {
                return ResourceManager.GetString("FailedSettingShimPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create tool shim for command &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string FailedToCreateShellShim {
            get {
                return ResourceManager.GetString("FailedToCreateShellShim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find staged tool package &apos;{0}&apos;..
        /// </summary>
        internal static string FailedToFindStagedToolPackage {
            get {
                return ResourceManager.GetString("FailedToFindStagedToolPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install tool package &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string FailedToInstallToolPackage {
            get {
                return ResourceManager.GetString("FailedToInstallToolPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read NuGet LockFile for tool package &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string FailedToReadNuGetLockFile {
            get {
                return ResourceManager.GetString("FailedToReadNuGetLockFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove tool shim for command &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string FailedToRemoveShellShim {
            get {
                return ResourceManager.GetString("FailedToRemoveShellShim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve tool configuration: {0}.
        /// </summary>
        internal static string FailedToRetrieveToolConfiguration {
            get {
                return ResourceManager.GetString("FailedToRetrieveToolConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add &apos;{0}&apos; to the PATH environment variable. Add this directory to your PATH to use tools installed with &apos;dotnet tool install&apos;..
        /// </summary>
        internal static string FailedToSetToolsPathEnvironmentVariable {
            get {
                return ResourceManager.GetString("FailedToSetToolsPathEnvironmentVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to uninstall tool package &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string FailedToUninstallToolPackage {
            get {
                return ResourceManager.GetString("FailedToUninstallToolPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File `{0}` not found..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format version is higher than supported. This tool may not be supported in this SDK version. Update your SDK..
        /// </summary>
        internal static string FormatVersionIsHigher {
            get {
                return ResourceManager.GetString("FormatVersionIsHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format version is malformed. This tool may not be supported in this SDK version. Contact the author of the tool..
        /// </summary>
        internal static string FormatVersionIsMalformed {
            get {
                return ResourceManager.GetString("FormatVersionIsMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format version is missing. This tool may not be supported in this SDK version. Contact the author of the tool..
        /// </summary>
        internal static string FormatVersionIsMissing {
            get {
                return ResourceManager.GetString("FormatVersionIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found a project `{0}` but it is invalid..
        /// </summary>
        internal static string FoundInvalidProject {
            get {
                return ResourceManager.GetString("FoundInvalidProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRAMEWORK.
        /// </summary>
        internal static string FrameworkArgumentName {
            get {
                return ResourceManager.GetString("FrameworkArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid project `{0}`..
        /// </summary>
        internal static string InvalidProject {
            get {
                return ResourceManager.GetString("InvalidProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid project `{0}`. {1}..
        /// </summary>
        internal static string InvalidProjectWithExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidProjectWithExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid solution `{0}`. {1}..
        /// </summary>
        internal static string InvalidSolutionFormatString {
            get {
                return ResourceManager.GetString("InvalidSolutionFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEVEL.
        /// </summary>
        internal static string LevelArgumentName {
            get {
                return ResourceManager.GetString("LevelArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        internal static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory parameter {0} missing for template {1}. .
        /// </summary>
        internal static string MandatoryParameterMissing {
            get {
                return ResourceManager.GetString("MandatoryParameterMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry point file &apos;{0}&apos; for command &apos;{1}&apos; was not found in the package..
        /// </summary>
        internal static string MissingToolEntryPointFile {
            get {
                return ResourceManager.GetString("MissingToolEntryPointFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings file &apos;DotnetToolSettings.xml&apos; was not found in the package..
        /// </summary>
        internal static string MissingToolSettingsFile {
            get {
                return ResourceManager.GetString("MissingToolSettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one packaged shim is available: {0}..
        /// </summary>
        internal static string MoreThanOnePackagedShimAvailable {
            get {
                return ResourceManager.GetString("MoreThanOnePackagedShimAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found more than one project in `{0}`. Specify which one to use..
        /// </summary>
        internal static string MoreThanOneProjectInDirectory {
            get {
                return ResourceManager.GetString("MoreThanOneProjectInDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found more than one solution file in {0}. Specify which one to use..
        /// </summary>
        internal static string MoreThanOneSolutionInDirectory {
            get {
                return ResourceManager.GetString("MoreThanOneSolutionInDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one {0} found..
        /// </summary>
        internal static string MoreThanOneXFound {
            get {
                return ResourceManager.GetString("MoreThanOneXFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No projects found in the solution..
        /// </summary>
        internal static string NoProjectsFound {
            get {
                return ResourceManager.GetString("NoProjectsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no {0} references in project {1}..
        /// </summary>
        internal static string NoReferencesFound {
            get {
                return ResourceManager.GetString("NoReferencesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not restore the project before building..
        /// </summary>
        internal static string NoRestoreDescription {
            get {
                return ResourceManager.GetString("NoRestoreDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to update..
        /// </summary>
        internal static string NothingToUpdate {
            get {
                return ResourceManager.GetString("NothingToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation is invalid..
        /// </summary>
        internal static string OperationInvalid {
            get {
                return ResourceManager.GetString("OperationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation {0} is invalid..
        /// </summary>
        internal static string OperationXInvalid {
            get {
                return ResourceManager.GetString("OperationXInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option {0} is invalid..
        /// </summary>
        internal static string OptionIsInvalid {
            get {
                return ResourceManager.GetString("OptionIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project to Project.
        /// </summary>
        internal static string P2P {
            get {
                return ResourceManager.GetString("P2P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project to Project reference.
        /// </summary>
        internal static string P2PReference {
            get {
                return ResourceManager.GetString("P2PReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        internal static string Package {
            get {
                return ResourceManager.GetString("Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package reference.
        /// </summary>
        internal static string PackageReference {
            get {
                return ResourceManager.GetString("PackageReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package reference `{0}` added to the project..
        /// </summary>
        internal static string PackageReferenceAddedToTheProject {
            get {
                return ResourceManager.GetString("PackageReferenceAddedToTheProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package reference `{0}` deleted..
        /// </summary>
        internal static string PackageReferenceDeleted {
            get {
                return ResourceManager.GetString("PackageReferenceDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package reference `{0}` does not exist..
        /// </summary>
        internal static string PackageReferenceDoesNotExist {
            get {
                return ResourceManager.GetString("PackageReferenceDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package reference `{0}` is invalid..
        /// </summary>
        internal static string PackageReferenceIsInvalid {
            get {
                return ResourceManager.GetString("PackageReferenceIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package reference `{0}` could not be found in the project..
        /// </summary>
        internal static string PackageReferenceNotFoundInTheProject {
            get {
                return ResourceManager.GetString("PackageReferenceNotFoundInTheProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference `{0}` deleted from the project..
        /// </summary>
        internal static string PackageReferenceRemoved {
            get {
                return ResourceManager.GetString("PackageReferenceRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of package `{0}` updated..
        /// </summary>
        internal static string PackageVersionUpdated {
            get {
                return ResourceManager.GetString("PackageVersionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of package `{0}` updated to `{1}`..
        /// </summary>
        internal static string PackageVersionUpdatedTo {
            get {
                return ResourceManager.GetString("PackageVersionUpdatedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify new version of the package..
        /// </summary>
        internal static string PleaseSpecifyNewVersion {
            get {
                return ResourceManager.GetString("PleaseSpecifyNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a version of the package..
        /// </summary>
        internal static string PleaseSpecifyVersion {
            get {
                return ResourceManager.GetString("PleaseSpecifyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify which package to update..
        /// </summary>
        internal static string PleaseSpecifyWhichPackageToUpdate {
            get {
                return ResourceManager.GetString("PleaseSpecifyWhichPackageToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        internal static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project `{0}` added to the solution..
        /// </summary>
        internal static string ProjectAddedToTheSolution {
            get {
                return ResourceManager.GetString("ProjectAddedToTheSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project {0} already has a reference `{1}`..
        /// </summary>
        internal static string ProjectAlreadyHasAPackageReference {
            get {
                return ResourceManager.GetString("ProjectAlreadyHasAPackageReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project already has a reference to `{0}`..
        /// </summary>
        internal static string ProjectAlreadyHasAreference {
            get {
                return ResourceManager.GetString("ProjectAlreadyHasAreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file to operate on. If a file is not specified, the command will search the current directory for one..
        /// </summary>
        internal static string ProjectArgumentDescription {
            get {
                return ResourceManager.GetString("ProjectArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROJECT.
        /// </summary>
        internal static string ProjectArgumentName {
            get {
                return ResourceManager.GetString("ProjectArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project `{0}` could not be evaluated. Evaluation failed with following error:
        ///{1}..
        /// </summary>
        internal static string ProjectCouldNotBeEvaluated {
            get {
                return ResourceManager.GetString("ProjectCouldNotBeEvaluated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project `{0}` deleted from solution..
        /// </summary>
        internal static string ProjectDeleted {
            get {
                return ResourceManager.GetString("ProjectDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project `{0}` does not exist..
        /// </summary>
        internal static string ProjectDoesNotExist {
            get {
                return ResourceManager.GetString("ProjectDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project `{0}` does not target framework `{1}`..
        /// </summary>
        internal static string ProjectDoesNotTargetFramework {
            get {
                return ResourceManager.GetString("ProjectDoesNotTargetFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project file.
        /// </summary>
        internal static string ProjectFile {
            get {
                return ResourceManager.GetString("ProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project `{0}` is invalid..
        /// </summary>
        internal static string ProjectIsInvalid {
            get {
                return ResourceManager.GetString("ProjectIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project `{0}` cannot be added due to incompatible targeted frameworks between the two projects. Review the project you are trying to add and verify that is compatible with the following targets:.
        /// </summary>
        internal static string ProjectNotCompatibleWithFrameworks {
            get {
                return ResourceManager.GetString("ProjectNotCompatibleWithFrameworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project `{0}` could not be found in the solution..
        /// </summary>
        internal static string ProjectNotFoundInTheSolution {
            get {
                return ResourceManager.GetString("ProjectNotFoundInTheSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project reference.
        /// </summary>
        internal static string ProjectReference {
            get {
                return ResourceManager.GetString("ProjectReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project reference `{0}` could not be found..
        /// </summary>
        internal static string ProjectReferenceCouldNotBeFound {
            get {
                return ResourceManager.GetString("ProjectReferenceCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project reference(s).
        /// </summary>
        internal static string ProjectReferenceOneOrMore {
            get {
                return ResourceManager.GetString("ProjectReferenceOneOrMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project reference `{0}` removed..
        /// </summary>
        internal static string ProjectReferenceRemoved {
            get {
                return ResourceManager.GetString("ProjectReferenceRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project `{0}` removed from solution..
        /// </summary>
        internal static string ProjectRemoved {
            get {
                return ResourceManager.GetString("ProjectRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project `{0}` removed from the solution..
        /// </summary>
        internal static string ProjectRemovedFromTheSolution {
            get {
                return ResourceManager.GetString("ProjectRemovedFromTheSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference `{0}` added to the project..
        /// </summary>
        internal static string ReferenceAddedToTheProject {
            get {
                return ResourceManager.GetString("ReferenceAddedToTheProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference `{0}` deleted..
        /// </summary>
        internal static string ReferenceDeleted {
            get {
                return ResourceManager.GetString("ReferenceDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference `{0}` is invalid..
        /// </summary>
        internal static string ReferenceIsInvalid {
            get {
                return ResourceManager.GetString("ReferenceIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified reference {0} does not exist in project {1}..
        /// </summary>
        internal static string ReferenceNotFoundInTheProject {
            get {
                return ResourceManager.GetString("ReferenceNotFoundInTheProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference `{0}` deleted from the project..
        /// </summary>
        internal static string ReferenceRemoved {
            get {
                return ResourceManager.GetString("ReferenceRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required argument {0} is invalid..
        /// </summary>
        internal static string RequiredArgumentIsInvalid {
            get {
                return ResourceManager.GetString("RequiredArgumentIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required argument {0} was not provided..
        /// </summary>
        internal static string RequiredArgumentNotPassed {
            get {
                return ResourceManager.GetString("RequiredArgumentNotPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required command was not provided..
        /// </summary>
        internal static string RequiredCommandNotPassed {
            get {
                return ResourceManager.GetString("RequiredCommandNotPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUNTIME_IDENTIFIER.
        /// </summary>
        internal static string RuntimeIdentifierArgumentName {
            get {
                return ResourceManager.GetString("RuntimeIdentifierArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; conflicts with an existing command from another tool..
        /// </summary>
        internal static string ShellShimConflict {
            get {
                return ResourceManager.GetString("ShellShimConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show command line help..
        /// </summary>
        internal static string ShowHelpDescription {
            get {
                return ResourceManager.GetString("ShowHelpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        internal static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution {0} already contains project {1}..
        /// </summary>
        internal static string SolutionAlreadyContainsProject {
            get {
                return ResourceManager.GetString("SolutionAlreadyContainsProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified solution file {0} does not exist, or there is no solution file in the directory..
        /// </summary>
        internal static string SolutionDoesNotExist {
            get {
                return ResourceManager.GetString("SolutionDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution file.
        /// </summary>
        internal static string SolutionFile {
            get {
                return ResourceManager.GetString("SolutionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project or solution file to operate on. If a file is not specified, the command will search the current directory for one..
        /// </summary>
        internal static string SolutionOrProjectArgumentDescription {
            get {
                return ResourceManager.GetString("SolutionOrProjectArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROJECT | SOLUTION.
        /// </summary>
        internal static string SolutionOrProjectArgumentName {
            get {
                return ResourceManager.GetString("SolutionOrProjectArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified alias {0} already exists. Specify a different alias..
        /// </summary>
        internal static string SpecifiedAliasExists {
            get {
                return ResourceManager.GetString("SpecifiedAliasExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified name {0} already exists. Specify a different name..
        /// </summary>
        internal static string SpecifiedNameExists {
            get {
                return ResourceManager.GetString("SpecifiedNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify at least one {0}..
        /// </summary>
        internal static string SpecifyAtLeastOne {
            get {
                return ResourceManager.GetString("SpecifyAtLeastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify at least one package to add..
        /// </summary>
        internal static string SpecifyAtLeastOnePackageReferenceToAdd {
            get {
                return ResourceManager.GetString("SpecifyAtLeastOnePackageReferenceToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify at least one package reference to remove..
        /// </summary>
        internal static string SpecifyAtLeastOnePackageReferenceToRemove {
            get {
                return ResourceManager.GetString("SpecifyAtLeastOnePackageReferenceToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify at least one project to add..
        /// </summary>
        internal static string SpecifyAtLeastOneProjectToAdd {
            get {
                return ResourceManager.GetString("SpecifyAtLeastOneProjectToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify at least one project to remove..
        /// </summary>
        internal static string SpecifyAtLeastOneProjectToRemove {
            get {
                return ResourceManager.GetString("SpecifyAtLeastOneProjectToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify at least one reference to add..
        /// </summary>
        internal static string SpecifyAtLeastOneReferenceToAdd {
            get {
                return ResourceManager.GetString("SpecifyAtLeastOneReferenceToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify at least one reference to remove..
        /// </summary>
        internal static string SpecifyAtLeastOneReferenceToRemove {
            get {
                return ResourceManager.GetString("SpecifyAtLeastOneReferenceToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template {0} created successfully. run &quot;dotnet restore&quot; to get started!.
        /// </summary>
        internal static string TemplateCreatedSuccessfully {
            get {
                return ResourceManager.GetString("TemplateCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template {0} could not be created. Error returned was: {1}..
        /// </summary>
        internal static string TemplateCreateError {
            get {
                return ResourceManager.GetString("TemplateCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template {0} installed successfully. You can use &quot;dotnet new {0}&quot; to get started with the new template..
        /// </summary>
        internal static string TemplateInstalledSuccesfully {
            get {
                return ResourceManager.GetString("TemplateInstalledSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template {0} could not be installed. Error returned was: {1}..
        /// </summary>
        internal static string TemplateInstallError {
            get {
                return ResourceManager.GetString("TemplateInstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool &apos;{0}&apos; (version &apos;{1}&apos;) is already installed..
        /// </summary>
        internal static string ToolPackageConflictPackageId {
            get {
                return ResourceManager.GetString("ToolPackageConflictPackageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; contains one or more of the following invalid characters: {1}..
        /// </summary>
        internal static string ToolSettingsInvalidCommandName {
            get {
                return ResourceManager.GetString("ToolSettingsInvalidCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command name &apos;{0}&apos; cannot begin with a leading dot (.)..
        /// </summary>
        internal static string ToolSettingsInvalidLeadingDotCommandName {
            get {
                return ResourceManager.GetString("ToolSettingsInvalidLeadingDotCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid XML: {0}.
        /// </summary>
        internal static string ToolSettingsInvalidXml {
            get {
                return ResourceManager.GetString("ToolSettingsInvalidXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool defines a command with a missing name setting..
        /// </summary>
        internal static string ToolSettingsMissingCommandName {
            get {
                return ResourceManager.GetString("ToolSettingsMissingCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; is missing an entry point setting..
        /// </summary>
        internal static string ToolSettingsMissingEntryPoint {
            get {
                return ResourceManager.GetString("ToolSettingsMissingEntryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one command is defined for the tool..
        /// </summary>
        internal static string ToolSettingsMoreThanOneCommand {
            get {
                return ResourceManager.GetString("ToolSettingsMoreThanOneCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; uses unsupported runner &apos;{1}&apos;.&quot;.
        /// </summary>
        internal static string ToolSettingsUnsupportedRunner {
            get {
                return ResourceManager.GetString("ToolSettingsUnsupportedRunner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project &apos;{0}&apos; has an unknown project type and cannot be added to the solution file. Contact your SDK provider for support..
        /// </summary>
        internal static string UnsupportedProjectType {
            get {
                return ResourceManager.GetString("UnsupportedProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the MSBuild verbosity level. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic]..
        /// </summary>
        internal static string VerbosityOptionDescription {
            get {
                return ResourceManager.GetString("VerbosityOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERSION_SUFFIX.
        /// </summary>
        internal static string VersionSuffixArgumentName {
            get {
                return ResourceManager.GetString("VersionSuffixArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} added to {1}..
        /// </summary>
        internal static string XAddedToY {
            get {
                return ResourceManager.GetString("XAddedToY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already contains {1}..
        /// </summary>
        internal static string XAlreadyContainsY {
            get {
                return ResourceManager.GetString("XAlreadyContainsY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already contains {1} `{2}`..
        /// </summary>
        internal static string XAlreadyContainsYZ {
            get {
                return ResourceManager.GetString("XAlreadyContainsYZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already has {1}..
        /// </summary>
        internal static string XAlreadyHasY {
            get {
                return ResourceManager.GetString("XAlreadyHasY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already has {1} `{2}`..
        /// </summary>
        internal static string XAlreadyHasYZ {
            get {
                return ResourceManager.GetString("XAlreadyHasYZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deleted from {1}..
        /// </summary>
        internal static string XDeletedFromY {
            get {
                return ResourceManager.GetString("XDeletedFromY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist..
        /// </summary>
        internal static string XDoesNotExist {
            get {
                return ResourceManager.GetString("XDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `{0}` found but is invalid..
        /// </summary>
        internal static string XFoundButInvalid {
            get {
                return ResourceManager.GetString("XFoundButInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid..
        /// </summary>
        internal static string XIsInvalid {
            get {
                return ResourceManager.GetString("XIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found..
        /// </summary>
        internal static string XNotFound {
            get {
                return ResourceManager.GetString("XNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not provided..
        /// </summary>
        internal static string XNotProvided {
            get {
                return ResourceManager.GetString("XNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} or {1} not found..
        /// </summary>
        internal static string XOrYNotFound {
            get {
                return ResourceManager.GetString("XOrYNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} or {1} not found in `{2}`..
        /// </summary>
        internal static string XOrYNotFoundInZ {
            get {
                return ResourceManager.GetString("XOrYNotFoundInZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} removed from {1}..
        /// </summary>
        internal static string XRemovedFromY {
            get {
                return ResourceManager.GetString("XRemovedFromY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully updated..
        /// </summary>
        internal static string XSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("XSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was not expected..
        /// </summary>
        internal static string XWasNotExpected {
            get {
                return ResourceManager.GetString("XWasNotExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} `{1}` does not exist..
        /// </summary>
        internal static string XYDoesNotExist {
            get {
                return ResourceManager.GetString("XYDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} `{1}` found but is invalid..
        /// </summary>
        internal static string XYFoundButInvalid {
            get {
                return ResourceManager.GetString("XYFoundButInvalid", resourceCulture);
            }
        }
    }
}
